# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('campeonato_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('slug_editorial', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('edicao_id', models.PositiveSmallIntegerField()),
                ('campeonato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.Campeonato')),
            ],
        ),
    ]
