# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-25 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edicao',
            new_name='Edicoe',
        ),
    ]
