# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0004_auto_20180125_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao_id', models.PositiveSmallIntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='edicoe',
            name='Campeonato',
        ),
        migrations.RemoveField(
            model_name='campeonato',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Edicoe',
        ),
        migrations.AddField(
            model_name='edicao',
            name='Campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.Campeonato'),
        ),
    ]
